tasks:
- s3tests:
    client.0:
      force-branch: ceph-master
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
              rgw sts key: abcdefghijklmnop
              rgw s3 auth use sts: true
              #rgw_s3_auth_order: "external,local,sts"
