meta:
- desc: "test basic ceph admin commands"
tasks:
- ssh_keys:
- print: "**** done ssh_keys"
- ceph-deploy:
    ceph-deploy-branch: wip-configparser-py2-fix
- print: "**** done ceph-deploy"
- workunit:
     clients:
        client.0:
           - ceph-tests/ceph-admin-commands.sh
- print: "**** done ceph-tests/ceph-admin-commands.sh"
